version: '2.0'

services:

  KIBANA:
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
      - 0.0.0.0:5601:5601
    cpuset: '1,2'
    mem_limit: 2000m

  ELASTIX:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    hostname: elasticsearch
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
    volumes:
      - /media/elastidata:/media/DATA/lastidata
    cpuset: '1,2,3'
    mem_limit: 5000m
